language: perl

perl:
  - "5.28"
  - "5.26"
  - "5.24"

before_install:
    # Install Dist::Zilla with plugins
    - "cpanm Dist::Zilla"
    - "dzil authordeps | xargs cpanm"

install:
    - "dzil listdeps | xargs cpanm"

script:
    - "dzil test --release"
